/**
 * Posts Manifest (auto-generated)
 */
export default [
  "B. Building A Second Brain.md",
  "B. Creativity, Inc..md",
  "B. Feel-Good Productivity.md",
  "B. Show Your Work.md",
  "B. Steal Like An Artist.md",
  "B. The Ride of a Lifetime.md",
  "B. The Speed of Trust.md",
  "Behavior Rebuilds What Talk Can’t.md",
  "Character and Competence The Two Pillars.md",
  "Don’t Set Yourself On Fire To Keep Others Warm.md",
  "Garden Readme.md",
  "Healing your inner child.md",
  "How to use Bear as a CMS.md",
  "In the creative process, job titles and hierarchy are meaningless.md",
  "It was her habit to build laughter out of inadequate materials..md",
  "It's not the critic who counts 2.md",
  "It's not the critic who counts.md",
  "Mistakes not to make as a leader.md",
  "Mistborn by Brandon Sanderson.md",
  "My last day at PwC.md",
  "Originality is Curated, Not Invented.md",
  "People only see the decisions I made not the choices I had.md",
  "Protecting the Ugly Baby.md",
  "The Braintrust Candor Without Command.md",
  "The Five Waves of Trust.md",
  "The UX request checklist.md",
  "The master in the art of living makes no distinction between work and play, labor and leisure. It’s all about pursuing excellence with passion and purpose.md",
  "The search for the best todo app.md",
  "Trust as a Cultural Operating System.md",
  "Trust is the Antidote to Fear.md",
  "When you’re building something avoid being in the world so you don’t get ideas and focus on the thing you are working on - Cal Newport.md",
  "“HONESTY IS AN EXPENSIVGIFT, DON'T EXPECT IT FROM CHEAP PEOPLE.”.md",
  "“My heart says yes but my calendar says no”.md",
  "“The palest ink is better than the best memory.” — Chinese Proverb.md",
  "“Whatever we aren’t changing, we are choosing”.md",
  "“anywhere belle face.”.md"
];
